version: "3.7"
services:
  mysql:
    image: mysql:8.0
    container_name: zbx-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpw
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbixpw
    command:
      --character-set-server=utf8mb4 --collation-server=utf8mb4_bin
      --log-bin-trust-function-creators=1
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"

  zabbix-server:
    image: zabbix/zabbix-server-mysql:latest
    container_name: zbx-server
    depends_on:
      - mysql
    environment:
      DB_SERVER_HOST: mysql
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbixpw
    ports:
      - "10051:10051"

  zabbix-web:
    image: zabbix/zabbix-web-nginx-mysql:latest
    container_name: zbx-web
    depends_on:
      - zabbix-server
      - mysql
    environment:
      DB_SERVER_HOST: mysql
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbixpw
      ZBX_SERVER_HOST: zbx-server
      PHP_TZ: "Asia/Manila"
    ports:
      - "8080:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./:/usr/share/nginx/html


volumes:
  mysql_data:
